models/TrxManual.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "trx_manual".
 *
 * @property int $id
 * @property string $number
 * @property int $location_id
 * @property string $reason
 * @property string $category
 * @property string $gold_category
 * @property string $description
 * @property int $quantity
 * @property int $unit
 * @property double $amount
 * @property string $jde_no
 * @property string $sold_to
 * @property string $deliver_to
 * @property string $transporter
 * @property string $vehicle_no
 * @property string $driver_name
 * @property string $notes
 * @property string $sender
 * @property string $status
 * @property int $is_active
 * @property int $created_by
 * @property int $created_at
 * @property int $updated_by
 * @property int $updated_at
 */
class TrxManual extends \yii\db\ActiveRecord
{
    const OPEN = "OPEN";
    const IN_PROGRESS = "IN_PROGRESS";
    const CLOSE = "CLOSE";
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trx_manual';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['number', 'location_id', 'reason', 'category', 'gold_category', 'sender', 'transporter'], 'required'],
            [['location_id', 'quantity', 'is_active', 'created_by', 'updated_by'], 'integer'],
            [['amount'], 'number'],
            [['number'], 'string', 'max' => 255],
            [['reason','category', 'gold_category','unit'], 'string', 'max' => 20],
            [['description'], 'string', 'max' => 225],
            [['jde_no'], 'string', 'max' => 64],
            [['sold_to', 'driver_name', 'notes'], 'string', 'max' => 150],
            [['deliver_to', 'transporter', 'vehicle_no', 'sender'], 'string', 'max' => 45],
            [['location_id'], 'exist', 'skipOnError' => true, 'targetClass' => MstLocation::className(), 'targetAttribute' => ['location_id' => 'id']],
            [['status','created_at'],'safe'],
        ];
    }
    
    public function getLocation()
    {
        return $this->hasOne(MstLocation::className(), ['id' => 'location_id']);
    }
    
    public function getManualReason() {
        return $this->hasOne(MstLookup::className(), ['code' => 'reason'])
                        ->where(['type' => 'ManualReason']);
    }
    
    public function getManualCategory() {
        return $this->hasOne(MstLookup::className(), ['code' => 'category']);
    }
    
    public function getManualGoldCategory() {
        return $this->hasOne(MstLookup::className(), ['code' => 'gold_category']);
    }
    
    public function getSenderBy()
    {
        return $this->hasOne(MstUser::className(), ['id' => 'sender']);
    }

    public function getTransportBy()
    {
        return $this->hasOne(MstCompany::className(), ['id' => 'transporter']);
    }
    
    public function getPostUser()
    {
        return $this->hasOne(MstUserProfile::className(), ['user_id' => 'created_by']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getManualWf()
    {
        return $this->hasMany(TrxManualWf::className(), ['manual_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'number' => 'Number',
            'location_id' => 'Location',
            'reason' => 'Reason',
            'category' => 'Category',
            'gold_category' => 'Gold Category',
            'description' => 'Description',
            'quantity' => 'Quantity',
            'unit' => 'Unit',
            'amount' => 'Amount',
            'jde_no' => 'Jde No',
            'sold_to' => 'Sold To',
            'deliver_to' => 'Deliver To',
            'transporter' => 'Transporter',
            'vehicle_no' => 'Vehicle No',
            'driver_name' => 'Driver Name',
            'notes' => 'Remarks',
            'sender' => 'Sender',
            'is_active' => 'Is Active',
            'created_by' => 'Post By',
            'created_at' => 'Post At',
            'updated_by' => 'Updated By',
            'updated_at' => 'Updated At',
        ];
    }
    
    public function beforeSave($insert) {
        if (!parent::beforeSave($insert)) {
            return false;
        }
        if ($this->isNewRecord) {
            $this->id = self::newId();
            $this->updated_at = date('Y-m-d H:i:s');
            $this->created_by = $this->updated_by = Yii::$app->user->identity->id;
            $this->status = self::OPEN;
        } else {
            $this->updated_at = date('Y-m-d H:i:s');
            $this->updated_by = Yii::$app->user->identity->id;
        }
        return true;
    }

    public static function newId() {
        $row = (new \yii\db\Query)
                ->select(['id'])
                ->from('trx_manual')
                ->max('id');
        return $row == null ? 1 : ($row + 1);
    }
    
    // workflow
    public static function updateWorkflow($id, $role){
        $result = false;
        // current
        $model = TrxManualWf::find()->where(['manual_id'=>$id, 'role_from'=>$role])->one();
        if($model !== null){
            $model->submited = 1;
            $model->update();
            // find manual
            $manual = TrxManual::findOne($id);
            
            //next
            $next = TrxManualWf::find()->where(['manual_id'=>$id, 'role_from'=>$model->role_to])->one();
            // jika masih ada role berikutnya, maka update next workflow
            if($next !== null){
                // update next workflow
                $next->ready = 1;
                $next->update();
                
                // update manual
                $manual->status = self::IN_PROGRESS;
                $manual->update();
                
            // jika sudah tidak ada maka close DD Manual
            }else{                
                $manual->status = self::CLOSE;
                $manual->update();
            }
            $result = true;
        }        
        return $result;
    }
    
    public static function rejectWorkflow($id, $role){
        $result = false;
        // current
        $model = TrxManualWf::find()->where(['manual_id'=>$id, 'role_from'=>$role])->one();
        if($model !== null){
            $model->ready = 0;
            $model->update();
            
            //before
            $next = TrxManualWf::find()->where(['manual_id'=>$id, 'position'=>($model->position - 1)])->one();
            if($next !== null){
                $next->submited = 0;
                $next->update();
            }
            $result = true;
        }        
        return $result;
    }

    public static function addWorkflow($id, $role) {
        $check = TrxManualWf::find()->where(['manual_id' => $id])->count();
        if ($check == 0) {
            $models = MstWorkflow::find()->where(['wf_type' => 'DD-MANUAL'])->orderBy('position')->all();
            foreach ($models as $model) {
                $item = new TrxManualWf();
                $item->manual_id = $id;
                $item->role_from = $model->role_from;
                $item->role_to = $model->role_to;
                $item->position = $model->position;
                $item->submited = 0;
                $item->ready = ($model->role_from == $role ? 1 : 0);
                $item->save();
            }
        }   
    }
    
    public static function statusList(){
        return [
            ['code' => self::OPEN, 'name'=>'Open'],
            ['code' => self::IN_PROGRESS, 'name'=>'In Progress'],
            ['code' => self::CLOSE, 'name'=>'Close'],
        ];
    }
    
    public static function responseStatus(){
        return [
            ['code' => self::IN_PROGRESS, 'name'=>'In Progress'],
        ];
    }
}

controllers/TrxManualController.php
<?php

namespace app\controllers;

use Yii;
use app\models\TrxManual;
use app\models\search\TrxManualSeach;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TrxManualController implements the CRUD actions for TrxManual model.
 */
class TrxManualController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    
    public function actionProses($id){
        
        $model = $this->findModel($id);
        
        $role = Yii::$app->user->identity->role;
        $proses = \app\models\MstWorkflow::labelProses('DD-MANUAL', $role);
                
        if (Yii::$app->request->post() && TrxManual::updateWorkflow($id, $role)) {
            return $this->redirect(['index']);

        }
        return $this->renderPartial('_proses', ['model' => $model, 'proses' =>$proses], false);
    }
    
    public function actionReject($id)
    {
        $role = Yii::$app->user->identity->role;
        TrxManual::rejectWorkflow($id, $role);

        return $this->redirect(['index']);
    }

    /**
     * Lists all TrxManual models.
     * @return mixed
     */
    public function actionList()
    {
        $searchModel = new TrxManualSeach();
        $role = Yii::$app->user->identity->role;
        $dataProvider = $searchModel->searchByRole(Yii::$app->request->queryParams, $role); 

        return $this->render('list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionIndex()
    {
        $searchModel = new TrxManualSeach();
        $role = Yii::$app->user->identity->role;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $role); 

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TrxManual model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->renderPartial('_view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionDetail($id)
    {
        return $this->render('detail', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TrxManual model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $role = Yii::$app->user->identity->role;
        $model = new TrxManual();

        if(Yii::$app->request->post()){
            $model->setAttributes(Yii::$app->request->post());
            $model->created_at = date('Y-m-d H:i:s', strtotime($model->created_at));
        }
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            TrxManual::addWorkflow($model->id, $role);
            return $this->redirect(['index']);
        }

        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing TrxManual model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $role = Yii::$app->user->identity->role;
        $model = $this->findModel($id);       
        $model->created_at = date('Y-m-d', strtotime($model->created_at));
        
        if(Yii::$app->request->post()){
            $model->setAttributes(Yii::$app->request->post());
            $model->created_at = date('Y-m-d H:i:s', strtotime($model->created_at));
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            //return ['result' => 'success']   
            $model->addWorkflow($id,$role);
            return $this->redirect(['index']);
        }

        return $this->render('update', ['model' => $model]);
    }

    /**
     * Deletes an existing TrxManual model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TrxManual model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TrxManual the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TrxManual::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/trx-manual/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use app\models\MstLocation;
use app\models\MstLookup;
use app\models\MstUser;
use app\models\MstCompany;

/* @var $this yii\web\View */
/* @var $model app\models\TrxManual */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="trx-manual-form">

    <?php
    $form = ActiveForm::begin([
                //'layout' => 'horizontal',
                'enableClientValidation' => false,
                'fieldConfig' => [
                    'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                    'horizontalCssClasses' => [
                        'label' => 'col-sm-2 col-md-2 col-lg-2',
                        'offset' => '',
                        'wrapper' => 'col-sm-10 col-md-10 col-lg-10',
                        'error' => '',
                        'hint' => '',
                    ],
                ],
    ]);
    ?>
    <?php if ($model->hasErrors()) : ?>
        <div class="callout callout-warning">
            <?= $form->errorSummary($model); ?>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?= $form->field($model, 'number')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'location_id')->dropDownList(ArrayHelper::map(MstLocation::listData2(), 'id', 'location_name'), ['class' => 'form-control select2', 'prompt' => '= Select Lokasi ='])
            ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'created_at', [
                'inputTemplate' => '<div class="input-group">{input}<div class="input-group-addon"><i class="fa fa-calendar"></i></div></div>',
                'horizontalCssClasses' => [
                    'label' => 'col-sm-4 col-md-4 col-lg-4',
                    'wrapper' => 'col-sm-8 col-md-8 col-lg-8',
                ],
            ])->textInput(['maxlength' => true, 'class' => 'form-control tanggal'])
            ?>
        </div>        
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'reason')
                ->dropDownList(
                    ArrayHelper::map(MstLookup::listData("ManualReason"), 'code', 'name'), 
                    [
                        'prompt' => '= Select Reason =', 
                        'class' => 'form-control reason select2'
                    ])?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'category', [
                'horizontalCssClasses' => [
                    'label' => 'col-sm-4',
                    'wrapper' => 'col-sm-8',
                ],
            ])->dropDownList(
                    empty($model->category) ? ArrayHelper::map(['empty' => 'empty'], 'id', 'value') : ArrayHelper::map(MstLookup::listData($model->reason), 'code', 'name'), 
                    [
                        'prompt' => '= Select Category =', 
                        'class' => 'form-control category select2'
                    ]);?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'gold_category')
                ->dropDownList(
                    empty($model->gold_category) ? ArrayHelper::map(['empty' => 'empty'], 'id', 'value') : ArrayHelper::map(MstLookup::listData($model->category), 'code', 'name'), 
                    [
                        'prompt' => '= Select Gold Category =', 
                        'class' => 'form-control gold-category select2'
                    ]);?>
        </div>
    </div>
    <?= $form->field($model, 'description')->textarea(['maxlength' => true, 'rows' => 4]) ?>
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'quantity')->textInput(['class' => 'form-control quantity'])
            ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'unit')->textInput(['class' => 'form-control unit'])
            ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">            
            <?=
            $form->field($model, 'amount')->textInput(['class' => 'form-control unit'])
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'jde_no')->textInput(['maxlength' => true])
            ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'sold_to')->textInput(['maxlength' => true])
            ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4"> 
            <?=
            $form->field($model, 'deliver_to')->textInput(['maxlength' => true])
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
             <?=
            $form->field($model, 'transporter')
                ->dropDownList(
                    ArrayHelper::map(MstCompany::listDataByType(MstCompany::TRANSPORTER_TYPE), 'id', 'name'), 
                    [
                        'class' => 'form-control select2',
                        'prompt' => '= Select Transporter ='
                    ]); ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'vehicle_no')->textInput(['maxlength' => true])
            ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'driver_name')->textInput(['maxlength' => true])
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
            <?= $form->field($model, 'notes')->textarea(['maxlength' => true, 'rows' => 4]) ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?=
            $form->field($model, 'sender', [
                'horizontalCssClasses' => [
                    'label' => 'col-sm-4 col-md-4 col-lg-4',
                    'wrapper' => 'col-sm-8 col-md-8 col-lg-8',
                ],
            ])->dropDownList(
                ArrayHelper::map(MstUser::listDataDefault(Yii::$app->user->identity->id), 'id', 'username'), 
                [
                    'class' => 'form-control select2',
                    'prompt' => '= Select Person ='
                ]);?>
        </div> 
    </div>

    <div class="modal-footer">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php ob_start(); // output buffer the javascript to register later   ?>
<script>
    $(document).ready(function () {
        $('.select2').select2();
        
        $(".tanggal").datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            setDate: new Date(),
        });
    });
    $(document).on('change', '.reason', function () {
        var id = $(this).val();
        $.ajax({
            url: '<?= Url::to(['ajax/get-lookup']) ?>',
            data: {'type': id},
            type: 'get',
            dataType: 'json',
            success: function (result) {
                $(document).find('.category').empty();
                $(document).find('.category').append('<option value="">= Pilih Kategori =</option>');
                $.each(result.data, function (index, item) {
                    $(document).find('.category').append('<option value="' + item.code + '">' + item.name + '</option>');
                });
            },
        });
    });

    $(document).on('change', '.category', function () {
        var id = $(this).val();
        $.ajax({
            url: '<?= Url::to(['ajax/get-lookup']) ?>',
            data: {'type': id},
            type: 'get',
            dataType: 'json',
            success: function (result) {
                $(document).find('.gold-category').empty();
                $(document).find('.gold-category').append('<option value="">= Pilih Gold Kategori =</option>');
                $.each(result.data, function (index, item) {
                    $(document).find('.gold-category').append('<option value="' + item.code + '">' + item.name + '</option>');
                });
            },
        });
    });
</script>
<?php $this->registerJs(str_replace(['<script>', '</script>'], '', ob_get_clean())); ?> 

views/trx-manual/_index.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\grid\GridView;
use yii\widgets\Pjax;

$currentController = Yii::$app->controller->id;
//Pjax::begin(['id' => $currentController . '-pjax']);
?>
<?=
GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'attribute'=>'created_at',
            'value' => function($data){
                return date('d-m-Y', strtotime($data->created_at));
            },
            'options' => ['class' => 'col-sm-1 col-md-1 col-lg-1 text-center'],
            'filter'=>Html::activeInput('text', $searchModel, 'created_at', ['class'=>'form-control tanggal'])
        ],
        'number',
        [
            'attribute' => 'location_id',
            'value' => 'location.location_name',
            'filter' => Html::activeDropDownList($searchModel, 'location_id', ArrayHelper::map(app\models\MstLocation::listData(), 'id', 'location_name'), ['class' => 'form-control select2', 'prompt' => '= Pilih Location=']),
            'options' => ['class' => 'col-sm-2 col-md-2 col-lg-2'],
        ],
        'description',
        [
            'attribute' => 'reason',
            'value' => 'manualReason.name',
            'filter' => Html::activeDropDownList($searchModel, 'reason', ArrayHelper::map(app\models\MstLookup::listData('ManualReason'), 'code', 'name'), ['class' => 'form-control select2', 'prompt' => '= Pilih Reason=']),
            'options' => ['class' => 'col-sm-2 col-md-2 col-lg-2'],
        ],
        /*
          [
          'attribute' => 'category',
          'value' => 'manualCategory.name',
          'filter' => Html::activeDropDownList($searchModel, 'category', ArrayHelper::map(app\models\MstLookup::listData('ManualCategory'), 'code', 'name'), ['class' => 'form-control', 'prompt' => '= Pilih Category=']),
          'options' => ['class' => 'col-sm-2 col-md-2 col-lg-2'],
          ], 
        'quantity',
        
        [
            'attribute' => 'sender',
            'value' => 'senderBy.username',
            'filter' => Html::activeDropDownList($searchModel, 'sender', ArrayHelper::map(app\models\MstUser::listData(), 'id', 'username'), ['class' => 'form-control select2', 'prompt' => '= Pilih Sender=']),
        ],
        */
        //'gold_category',
        //'description',
        //'unit',
        //'amount',
        //'jde_no',
        //'sold_to',
        //'deliver_to',
        //'transporter',
        //'vehicle_no',
        //'driver_name',
        //'notes',
        //'sender',
        //'is_active',
        //'created_by',
        //'created_at',
        //'updated_by',
        //'updated_at',
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view}',
            'options' => ['style' => 'width:50px;'],
            'buttons' => [
                'view' => function($url, $model, $key) {
                    return Html::button('<span class="fa fa-eye"></span>', [
                                'class' => 'btn btn-xs btn-success btn-view',
                                'title' => Yii::t('yii', 'View Data'),
                                'value' => $key,
                    ]);
                },
            ],
        ],
    ],
]);
?>
<?php //Pjax::end(); ?>

views/trx-manual/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\TrxForm */

$this->title = Yii::t('app', 'New DD Manual');
$this->params['breadcrumbs'][] = ['label' => 'DD Manual', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-info trx-callcenter-index">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?> Form</h3>  
    </div>
    <div class="box-body">
        <?= $this->render('_form', ['model' => $model]) ?>
    </div>
</div>

views/trx-manual/detail.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\TrxForm */

$this->title = Yii::t('app', 'Deatil DD Manual');
$this->params['breadcrumbs'][] = ['label' => 'DD Manual', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->params['breadcrumbs'][] = $model->number;
?>
<div class="invoice" style="margin:0px;">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h3 class="page-header">
                <i class="fa fa-globe"></i>
                <?= $model->description;?>
                <small class="pull-right">Date : <?= date('d-m-Y h:m', strtotime($model->created_at));?></small>
            </h3>
        </div>
    </div>
    <div class="row invoice-info">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 invoice-col">
            From <br>
            <?php echo "<b>". $model->transportBy->company_name ."</b><br>"; ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 invoice-col">
            Deliver To :<br>
            <?php echo "<b>". $model->deliver_to."</b><br>"; ?>
            <br>
            Sold To : <br>
            <?php echo "<b>". (empty($model->sold_to) ? "-" : $model->sold_to)."</b><br>"; ?>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 invoice-col">
            <?php 
                echo "<b>Number :#". $model->number ."</b><br>".
                "Reason :<br><b>". $model->manualReason->name ."</b><br>".
                "Category:<br><b>". $model->manualCategory->name ."</b><br>"; 
            ?>
        </div>
    </div>
    <div class="row">
        <div calss="col-xs-12 col-sm-12 col-md-12 col-lg-12 table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width:10%;">Quantity</th>
                        <th style="width:10%;">Unit</th>
                        <th style="width:10%;">JDE No.</th>
                        <th>Description</th>
                        <th style="width:10%;">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?= $model->quantity; ?></td>
                        <td><?= $model->unit; ?></td>
                        <td><?= $model->jde_no; ?></td>
                        <td><?= $model->description; ?></td>
                        <td class="text-right"><?= $model->amount; ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <p class="lead">Remark :</p>
            <?php if(!empty($model->notes)) : ?>
            <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                <?= $model->notes; ?>
            </p>
            <?php endif;?>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <p class="lead">Amount :</p>
            <div class="table-responsive">
                <table class="table">
                    <tbody>
                        <tr>
                            <th style="width:50%;">Amount </th>
                            <th><?= $model->amount; ?></th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

views/trx-manual/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\TrxForm */

$this->title = Yii::t('app', 'Update DD Manual');
$this->params['breadcrumbs'][] = ['label' => 'DD Manual', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-info trx-callcenter-index">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?> Form</h3>  
    </div>
    <div class="box-body">
        <?= $this->render('_form', ['model' => $model]) ?>
    </div>
</div>