models/MstUser.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "mst_user".
 *
 * @property int $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 *
 * @property TrxConversationDetail[] $trxConversationDetails
 */
class MstUser extends ActiveRecord implements IdentityInterface {

    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 10;

    public $password;

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'mst_user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['username', 'password', 'email'],'required','on'=>'insert'],
            [['id','username','status'],'required','on'=>'disabled'],
            ['username', 'filter', 'filter' => 'trim'],
            ['username', 'unique', 'targetClass' => 'app\models\MstUser', 'message' => 'This username has already been taken.'],
            ['username', 'string', 'min' => 2, 'max' => 255],
            ['email', 'filter', 'filter' => 'trim'],
            ['email', 'email'],
            //['email', 'unique', 'targetClass' => 'app\models\MstUser', 'message' => 'This email address has already been taken.'],
            //['password', 'required'],
            //['password', 'string', 'min' => 6],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['auth_key'], 'string', 'max' => 32],
            [['password_hash', 'password_reset_token', 'email'], 'string', 'max' => 255],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE]],
            // password save
            [['password'],'safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'username' => 'User ID',
            'password' => 'Password',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function getMstUserProfile() {
        return $this->hasOne(MstUserProfile::className(), ['user_id' => 'id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrxConversationDetails() {
        return $this->hasMany(TrxConversationDetail::className(), ['for' => 'id']);
    }

    public function beforeSave($insert) {
        if (!parent::beforeSave($insert)) {
            return false;
        }        
        //$this->setPassword($this->password);
        $this->generateAuthKey();
        if ($this->isNewRecord) {
            $this->id = self::newId();
            $this->created_at = $this->updated_at = time();      
        } else {
            $this->updated_at = time();
        }
        return true;
    }

    public static function newId() {
        $row = (new \yii\db\Query)
                ->select(['id'])
                ->from('mst_user')
                ->max('id');
        return $row == null ? 1 : ($row + 1);
    }

    public static function listConversation() {
        $items = array();
        $models = self::find()->where(['not in', 'id', [Yii::$app->user->identity->id]])->all();
        if ($models !== null) {
            foreach ($models as $model){
                $items[] =[ 'id'=>$model->id, 'username'=>$model->fullname]; 
            }
        }
        return $items;
    }

    public static function listData() {
        $items = array();
        $models = self::find()->where(['status'=> self::STATUS_ACTIVE])->orderBy('username')->all();
        if ($models !== null) {
            foreach ($models as $model){
                $items[] =[ 'id'=>$model->id, 'username'=>$model->fullname]; 
            }
        } 
        return $items;
    }
    
    public static function listDataDefault($id) {
        $items = array();
        $current = self::findOne($id);
        $items[] =[ 'id'=>$current->id, 'username'=>$current->fullname]; 
        
        // set loop
        $models = self::find()
                ->andWhere(['and','status',self::STATUS_ACTIVE])
                ->andWhere(['not in','id',$id])->orderBy('username')->all();
        if ($models !== null) {
            foreach ($models as $model){
                $items[] =[ 'id'=>$model->id, 'username'=>$model->fullname]; 
            }
        } 
        return $items;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id) {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null) {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username) {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token) {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
                    'password_reset_token' => $token,
                    'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token) {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId() {
        return $this->getPrimaryKey();
    }

    public function getRole() {
        $result = "";
        $roleModel = Yii::$app->db
                ->createCommand("select * from auth_assignment where user_id='" . $this->id . "'")
                ->queryOne();
        $result = $roleModel['item_name'];
        return $result;
    }
    
    public function getListRole() {
        $result = "";
        $roleModel = Yii::$app->db
                ->createCommand("select * from auth_assignment where user_id='" . $this->id . "'")
                ->queryAll();
        foreach($roleModel as $row){
            $result .= $row['item_name'].", ";
        }
        return $result;
    }
    
    public function getFullname(){
        return $this->mstUserProfile == null ? $this->username : $this->mstUserProfile->full_name;
    }
    
    public function getImage(){
        return $this->mstUserProfile == null ? "/profile/user2-160x160.jpg" : 
                ($this->mstUserProfile->image_path==null ? "/profile/user2-160x160.jpg" : $this->mstUserProfile->image_path);
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey() {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey) {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password) {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password) {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey() {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken() {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken() {
        $this->password_reset_token = null;
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\form\Login;
use app\models\ContactForm;

use yii\helpers\FileHelper;
use yii\imagine\Image;
use yii\helpers\Json;
use Imagine\Image\Box;
use Imagine\Image\Point;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        $this->layout='//mainLogin';
        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }

        $model = new Login();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                    'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionProfile(){
        $userId = Yii::$app->user->id;
        $model = \app\models\MstUserProfile::findOne($userId);        
        $model->setScenario("profile");
        if ($model->load(Yii::$app->request->post()))
        {   
            $model->image = \yii\web\UploadedFile::getInstance($model, 'image');
             // open image
            $image = Image::getImagine()->open($model->image->tempName);

            // rendering information about crop of ONE option 
            $temp = Json::decode($model->crop_info)[0];
            $cropInfo = array();
            $cropInfo['dWidth'] = $temp['dWidth']; //new width image
            $cropInfo['dHeight'] = $temp['dHeight']; //new height image
            $cropInfo['x'] = abs($temp['x']); //begin position of frame crop by X
            $cropInfo['y'] = abs($temp['y']); //begin position of frame crop by Y
            $cropInfo['width'] = $temp['width']; //width of cropped image
            $cropInfo['height'] = $temp['height']; //height of cropped image
            // Properties bolow we don't use in this example
            //$cropInfo['ratio'] = $cropInfo['ratio'] == 0 ? 1.0 : (float)$cropInfo['ratio']; //ratio image. 

            //delete old images
            $oldImages = FileHelper::findFiles(Yii::getAlias('@webroot/profile'), [
                'only' => [
                    $model->user_id . '.*',
                    'user_' . $model->user_id . '.*',
                ], 
            ]);
            for ($i = 0; $i != count($oldImages); $i++) {
                @unlink($oldImages[$i]);
            }

            //saving thumbnail
            $newSizeThumb = new Box($cropInfo['dWidth'], $cropInfo['dHeight']);
            $cropSizeThumb = new Box($cropInfo['width'], $cropInfo['height']); //frame size of crop
            $cropPointThumb = new Point($cropInfo['x'], $cropInfo['y']);
            $pathThumbImage = Yii::getAlias('@webroot/profile') . '/user_' . $userId . '.' . $model->image->getExtension();  

            $image->resize($newSizeThumb)
                ->crop($cropPointThumb, $cropSizeThumb)
                ->save($pathThumbImage, ['quality' => 100]);
            $model->image_path = '/profile/user_'. $userId . '.' . $model->image->getExtension();
            if($model->save()){
                return $this->goHome();
            }else {
                 return $this->render('profile',['model' => $model, 'data'=>$cropInfo]);
            }
        }
        return $this->render('profile',['model' => $model]);
    }
}

views/site/_profile-info.php
<div class="box box-primary">
    <div class="box-body box-profile">
        <img class="profile-user-img img-responsive img-circle" src="<?= Yii::getAlias('@web') . $model->images_path; ?>" alt="User profile picture">

        <h3 class="profile-username text-center"><?= $model->role ?></h3>

        <p class="text-muted text-center">&nbsp;</p>

        <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
                <b>Nama Lengkap </b> <a class="pull-right"><?= $model->full_name ?></a>
            </li>
            <li class="list-group-item">
                <b>User Aplikasi</b> <a class="pull-right"><?= $model->username; ?></a>
            </li>
            <li class="list-group-item">
                &nbsp;
            </li>
            <li class="list-group-item">
                &nbsp;
            </li>
        </ul>

        <button type="button" class="btn btn-primary btn-block" id="btn-update"><b>Update Profile</b></button>
    </div>
    <!-- /.box-body -->
</div>

views/site/_profile-update.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use bupy7\cropbox\CropboxWidget;
?>
<div class="box box-info site-signup">
    <div class="box-header with-border">
        <h3 class="box-title">Update Profile</h3>
    </div>
    <div class="box-body">
        <?php
        $form = ActiveForm::begin([
                    'id' => 'form-update',
                    'layout' => 'horizontal',
                    'enableClientValidation' => false,
                    'options' => ['enctype' => 'multipart/form-data'],
        ]);
        ?>
        <?= $form->errorSummary($model,['header'=>''])?>
        <?=
        $form->field($model, 'image')->widget(CropboxWidget::className(), [
            'croppedDataAttribute' => 'crop_info',
            'croppedImagesUrl' => (empty($model->images_path) ? '' : Yii::getAlias('@web') . $model->images_path),
        ]);
        ?>

        <?php /* $form->field($model, 'full_name')->textInput(['maxlength' => true])*/ ?>

        <?php /*$form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'email') ?>

        <?= $form->field($model, 'password')->passwordInput() */?>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-8">
                <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Dashboard';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Welcome!</h1>

        <p class="lead">You have successfully login at this application.</p>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- /.login-logo -->
<div class="login-box-body">

    <p class="login-box-msg">Sign in to start your session</p>

    <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
    <?=
    $form->field($model, 'username', [
        'options' => ['class' => 'form-group has-feedback'],
        'inputTemplate' => '{input}<span class="glyphicon glyphicon-user form-control-feedback"></span>',
    ])->textInput(['autofocus' => true, 'placeholder' => 'Username'])->label(false)
    ?>
    <?=
    $form->field($model, 'password', [
        'options' => ['class' => 'form-group has-feedback'],
        'inputTemplate' => '{input}<span class="glyphicon glyphicon-lock form-control-feedback"></span>',
    ])->passwordInput(['autofocus' => true, 'placeholder' => 'Password'])->label(false)
    ?>
    <div class="row">
        <div class="col-xs-8">
            <?= $form->field($model, 'rememberMe',[
                'options' => ['class' => 'checkbox icheck'],                  
            ])->checkbox([
                'template' => '{beginLabel}{input} {labelTitle}{endLabel}{error}{hint}',
            ]) ?>           
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
        </div>
        <!-- /.col -->
    </div>
    
    <!--div style="color:#999;margin:1em 0">
        If you forgot your password you can <?= Html::a('reset it', ['user/request-password-reset']) ?>.
        For new user you can <?= Html::a('signup', ['user/signup']) ?>.
    </div-->    
<?php ActiveForm::end(); ?>
<?= Html::a('I forgot my password', ['/user/request-password-reset']) ?>
</div>

views/site/profile.php
<?php
$this->title = 'Profile User';
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- Profile Image -->
<?= $this->render('_profile-update', ['model' => $model]); ?>
<?php ob_start(); ?>
<script>
    $('#btn-update').click(function(){
        $('#profile-update').show();
    });
</script>
<?php $this->registerJs(str_replace(['<script>', '</script>'], '', ob_get_clean())); ?>