models/TrxHazard.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "trx_hazard".
 *
 * @property int $id
 * @property string $title
 * @property int $location_id
 * @property int $area_id
 * @property string $area_other
 * @property string $risk
 * @property string $posibility
 * @property string $risk_level
 * @property string $description
 * @property string $status
 * @property int $is_active
 * @property int $created_by
 * @property int $created_at
 * @property int $updated_by
 * @property int $updated_at
 *
 * @property MstArea $area
 * @property MstLocation $location
 * @property TrxHazardDetail[] $trxHazardDetails
 */
class TrxHazard extends \yii\db\ActiveRecord
{
    const OPEN = "OPEN";
    const IN_PROGRESS = "IN_PROGRESS";
    const CLOSE = "CLOSE";
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trx_hazard';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'location_id', 'area_id', 'area_other', 'risk', 'posibility', 'risk_level', 'description'], 'required'],
            [['location_id', 'area_id', 'is_active', 'created_by',  'updated_by'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['area_other'], 'string', 'max' => 45],
            [['risk', 'posibility', 'risk_level', 'status'], 'string', 'max' => 20],
            [['description'], 'string', 'max' => 225],
            [['area_id'], 'exist', 'skipOnError' => true, 'targetClass' => MstArea::className(), 'targetAttribute' => ['area_id' => 'id']],
            [['location_id'], 'exist', 'skipOnError' => true, 'targetClass' => MstLocation::className(), 'targetAttribute' => ['location_id' => 'id']],
            [['risk_level'],'safe'],
            [['created_at','updated_at'],'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Topik',
            'location_id' => 'Lokasi',
            'area_id' => 'Area',
            'area_other' => 'Detail Area',
            'risk' => 'Konsekuensi',
            'posibility' => 'Kemungkinan',
            'risk_level' => 'Tingkat Resiko',
            'description' => 'Penjelasan Singkat',
            'status' => 'Status',
            'is_active' => 'Is Active',
            'created_by' => 'Post By',
            'created_at' => 'Created At',
            'updated_by' => 'Updated By',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArea()
    {
        return $this->hasOne(MstArea::className(), ['id' => 'area_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocation()
    {
        return $this->hasOne(MstLocation::className(), ['id' => 'location_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrxHazardDetails()
    {
        return $this->hasMany(TrxHazardDetail::className(), ['hazard_id' => 'id']);
    }
    
    public function getTrxHazardComments() {
        return $this->hasMany(TrxHazardComment::className(), ['hazard_id' => 'id']);
    }
    
    public function getPostBy(){
        return $this->hasOne(MstUser::className(), ['id' => 'created_by']);
    }
    
    public function getPostUser()
    {
        return $this->hasOne(MstUserProfile::className(), ['user_id' => 'created_by']);
    }
    
    
    public function getPosibilityLookup() {
        return $this->hasOne(MstLookup::className(), ['code' => 'posibility'])
                        ->where(['type' => 'HazardPosibility']);
    }
    
    public function getRiskLookup() {
        return $this->hasOne(MstLookup::className(), ['code' => 'risk'])
                        ->where(['type' => 'HazardRisk']);
    }
    
    public function getLevelLookupMap() {
        $model = MstLookupMap::find()->where(['code_from' => $this->risk, 'code_to' => $this->posibility])->one();
        if ($model !== null)
            return $model;
        else
            return null;
    }
    
    public function beforeSave($insert) {
        if (!parent::beforeSave($insert)) {
            return false;
        }
        if ($this->isNewRecord) {
            $this->id = self::newId();
            //$this->created_at = 
            $this->updated_at = date('Y-m-d H:i:s');
            $this->created_by = $this->updated_by = Yii::$app->user->identity->id;
            $this->status = self::OPEN;
        } else {
            $this->updated_at = date('Y-m-d H:i:s');
            $this->updated_by = Yii::$app->user->identity->id;
        }
        return true;
    }

    public static function newId() {
        $row = (new \yii\db\Query)
                ->select(['id'])
                ->from('trx_hazard')
                ->max('id');
        return $row == null ? 1 : ($row + 1);
    }
    
    public static function statusList(){
        return [
            ['code' => self::OPEN, 'name'=>'Open'],
            ['code' => self::IN_PROGRESS, 'name'=>'In Progress'],
            ['code' => self::CLOSE, 'name'=>'Close'],
        ];
    }
    
    public static function responseStatus(){
        return [
            ['code' => self::IN_PROGRESS, 'name'=>'In Progress'],
        ];
    }
    
    public function getAllowComment() {
        $result = false;
        $userId = Yii::$app->user->identity->id;
        $model = TrxHazardDetail::find()->where(['hazard_id' => $this->id, 'for_user' => $userId])->count();
        if ($model > 0) {
            $result = true;
        }
        return $result;
    }
    
    public function getHasFollowUp(){
        $result = false;
        $userId = Yii::$app->user->identity->id;
        $model = TrxHazardDetail::find()->where(['hazard_id' => $this->id, 'for_user' => $userId, 'status'=>self::OPEN])->count();
        if ($model > 0) {
            $result = true;
        }
        return $result;
    }
    
    public function getIsAuthor() {
        $result = false;
        $userId = Yii::$app->user->identity->id;
        if ($userId == $this->created_by) {
            $result = true;
        }
        return $result;
    }
    
    public function getCommentCount() {
        return $this->hasMany(TrxHazardComment::className(), ['hazard_id' => 'id'])->count();
    }
    
    public function getIsClose(){
        return $this->status == self::CLOSE ? true : false;
    }
    
    public static function countByUser() {
        $result = 0;
        $userId = Yii::$app->user->identity->id;
        $model = TrxHazardDetail::find()->where(['for_user' => $userId, 'status' => self::OPEN])->count();
        if ($model > 0) {
            $result = $model;
        }
        return $result;
    }

    public static function listByUser() {
        $userId = Yii::$app->user->identity->id;
        $models = TrxHazard::find()
                ->joinWith(['trxHazardDetails d'])
                ->where(['d.for_user' => $userId, 'd.status' => self::OPEN])
                ->all();
        return $models;
    }

    /**
     * Sends an email with a link, for resetting the password.
     *
     * @return boolean whether the email was send
     */
    public function sendEmail()
    {
        $location = MstLocation::findOne($this->location_id);
        $userInput = ($this->postUser == null ? Yii::$app->user->identity->username : $this->postUser->full_name);
        $cc = explode(";", $location->safety_email);
        $resetLink = Url::to(['trx-hazard/detail','id'=>$this->id], true);
        $receivers = $this->trxHazardDetails;
        foreach($receivers as $receiver){
            $receiverName = $receiver->forUserProfile == null ? $receiver->forUser->email : $receiver->forUserProfile->full_name;
            $receiverEmail = $receiver->forUser->email;
            Yii::$app->mailer->compose(['html' => 'safety-html', 'text' => 'safety-text'], 
                    ['resetLink' => $resetLink, 'receiver'=>$receiverName, 'userInput'=>$userInput, 'safetyType'=>'Hazard'])
                    ->setFrom([Yii::$app->params['supportEmail'] => Yii::$app->params['supportName']])
                    ->setCc($cc)
                    ->setTo($receiverEmail)
                    ->setSubject('Hazard -  ' . $this->title)
                    ->send();
        }

        return false;
    }
}

controllers/TrxNearmissController.php
<?php

namespace app\controllers;

use Yii;
use app\models\TrxNearmiss;
use app\models\TrxNearmissDetail;
use app\models\TrxNearmissComment;
use app\models\search\TrxNearmissSearch;
use app\models\form\TrxNearmissForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TrxNearmissController implements the CRUD actions for TrxNearmiss model.
 */
class TrxNearmissController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TrxNearmiss models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new TrxNearmissSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionList() {
        $searchModel = new TrxNearmissSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('list', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TrxNearmiss model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDetail($id) {
        return $this->render('detail', [
                    'model' => $this->findModel($id),
        ]);
    }

    public function actionView($id) {
        return $this->renderPartial('_view', [
                    'model' => $this->findModel($id),
        ]);
    }

    public function actionClosing($id) {
        $model = New TrxNearmissComment();
        $model->loadDefaultValues();
        $model->nearmiss_id = $id;
        $model->status = TrxNearmiss::CLOSE;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $parent = TrxNearmiss::findOne($id);
            if ($parent !== null) {
                $parent->status = TrxNearmiss::CLOSE;
                $parent->update();
            }
            return $this->redirect(['index']);
        }
        return $this->render('closing', [
                    'model' => $model,
        ]);
    }

    public function actionResponse($id) {
        $userId = Yii::$app->user->identity->id;
        $model = $this->findModel($id);
        $detail = $this->findDetail($id, $userId);

        $comment = New TrxNearmissComment();
        $comment->nearmiss_id = $id;
        if ($comment->load(Yii::$app->request->post()) && $comment->save()) {
            $this->updateStatus($detail->id, $comment->status);

            return $this->redirect(['index']);
        }

        return $this->render('response', [
                    'model' => $model,
                    'detail' => $detail,
                    'comment' => $comment,
        ]);
    }

    /**
     * Creates a new TrxNearmiss model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new TrxNearmissForm();
        $model->trxNearmiss = new TrxNearmiss;
        $model->trxNearmiss->loadDefaultValues();        
        $model->setAttributes(Yii::$app->request->post());

        if (Yii::$app->request->post() && $model->save()) {
            //\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            //return ['result' => 'success'];
            if($model->trxNearmiss->risk_level=='HIGH'){
                $model->trxNearmiss->sendMail();
            }
            return $this->redirect(['index']);
        }

        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing TrxNearmiss model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = new TrxNearmissForm();
        $model->trxNearmiss = $this->findModel($id);
        $model->setAttributes(Yii::$app->request->post());

        if (Yii::$app->request->post() && $model->save()) {
            //\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            //return ['result' => 'success'];
            return $this->redirect(['index']);
        }

        return $this->render('update', ['model' => $model]);
    }

    /**
     * Deletes an existing TrxNearmiss model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TrxNearmiss model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TrxNearmiss the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function updateStatus($id, $status) {
        $model = TrxNearmissDetail::findOne($id);
        if ($model !== null) {
            $model->status = $status;
            $model->update();
        }
    }

    protected function findModel($id) {
        if (($model = TrxNearmiss::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    protected function findDetail($id, $userId) {
        if (($model = TrxNearmissDetail::find()->where(['nearmiss_id' => $id, 'for_user' => $userId])->one()) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

}

views/trx-nearmiss/_comment.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\TrxHazard;

/* @var $this yii\web\View */
/* @var $model app\models\search\MstTersangkaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<?php
$form = ActiveForm::begin([
            'id' => 'form-safety-comment',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'offset' => 'col-sm-offset-0',
                    'wrapper' => 'col-sm-12 col-md-12',
                    'error' => '',
                    'hint' => '',
                ],
            ],
        ]);
?>
<?php if ($model->hasErrors()) : ?>
    <div class="callout callout-warning">
        <?= $form->errorSummary($model); ?>
    </div>
<?php endif; ?>
<div class="row">
    <div class="col-sm-8 col-md-8 col-lg-8">
        <?= $form->field($model, 'content')->textArea(['placeholder' => 'Type Comment', 'rows' => 4]) ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?=
        $form->field($model, 'status')->dropDownList(ArrayHelper::map(TrxHazard::responseStatus(), 'code', 'name'))
        ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?= $form->field($model, 'nearmiss_id')->hiddenInput()->label(false) ?>
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

</div>

views/trx-nearmiss/_item.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\HtmlPurifier;
use yii\helpers\Inflector;

$imageUrl = Yii::getAlias('@web').'/img/user1-128x128.jpg';
if(!empty($model->posUser->image_path) && file_exists(Yii::getAlias('@web').$model->posUser->image_path)){
    $imageUrl = Yii::getAlias('@web').$model->posUser->image_path;
}
?>
<div class="box box-info trx-conversation-index">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::a(Inflector::camel2words($model->title), ['detail', 'id' => $model->id]) ?></h3>       
    </div>
    <div class="box-body">
        <!-- Post -->
        <div class="post">
            <div class="user-block">
                <img class="img-circle img-bordered-sm" src="<?= $imageUrl; ?>" alt="user image">
                <span class="username">
                    <a href="#"><?= $model->postBy->fullname ?></a>
                </span>
                <span class="description">
                    <i>Lokasi :</i>
                    <strong><i class="fa fa fa-map-marker margin-r-5"></i><?= $model->location->location_name ?></strong>
                    , <i>Area :</i>
                    <strong><?= $model->area->area_name; ?> </strong>
                    , <i>Posting :</i> <?= date('d-m-Y H:i:s', strtotime($model->created_at)); ?>
                </span>
            </div>
            <p> 
                <!-- /.user-block -->
                <?= HtmlPurifier::process($model->description) ?> 
            </p>
            <ul class="list-inline">
                <li><a href="<?= Url::to(['trx-nearmiss/detail','id'=>$model->id])?>" class="btn btn-info btn-xs"><i class="fa fa-eye margin-r-5"></i> Detail</a></li>
                <?php if($model->hasFollowUp) : ?>
                <li><a href="<?= Url::to(['trx-nearmiss/response','id'=>$model->id])?>" class="btn btn-success btn-xs"><i class="fa fa-reply-all margin-r-5"></i> Need Response</a></li>
                <?php endif;?>
                <li class="pull-right">
                    <a href="<?= Url::to(['trx-nearmiss/detail','id'=>$model->id])?>" class="link-black text-sm"><i class="fa fa-comments-o margin-r-5"></i> Follow Up(<?= $model->commentCount ?>)</a>
                </li>
            </ul>
        </div>
        <!-- /.post -->
    </div>
    <div class="overlay" style="display:none;">
        <i class="fa fa-refresh fa-spin"></i>
    </div>
</div>

views/trx-nearmiss/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\TrxForm */

$this->title = Yii::t('app', 'New Near Miss');
$this->params['breadcrumbs'][] = ['label' => 'Near Miss', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-info trx-callcenter-index">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?> Form</h3>  
    </div>
    <div class="box-body">
        <?= $this->render('_form', ['model' => $model]) ?>
    </div>
</div>

views/trx-nearmiss/detail.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\HtmlPurifier;

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Nearmiss'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label'=> Yii::t('app','Detail')];
$imageUrl = Yii::getAlias('@web').'/img/user1-128x128.jpg';
if(!empty($model->posUser->image_path) && file_exists(Yii::getAlias('@web').$model->posUser->image_path)){
    $imageUrl = Yii::getAlias('@web').$model->posUser->image_path;
}
$currentController = Yii::$app->controller->id;
?>
<div class="box box-info trx-conversation-index">
    <div class="box-header with-border">
        <div class="user-block">
            <img class="img-circle img-bordered-sm" src="<?= $imageUrl; ?>" alt="user image">
            <span class="username">
                <a href="#"><?= $model->postBy->fullname ?></a>
            </span>
            <span class="description">
                <i>Lokasi :</i>
                <strong><i class="fa fa fa-map-marker margin-r-5"></i><?= $model->location->location_name ?></strong>
                , <i>Area :</i>
                <strong><?= $model->area->area_name; ?> </strong>
                , <i>Posting :</i> <?= date('d-m-Y H:i:s', strtotime($model->created_at)); ?>
            </span>
        </div>      
        <div class="box-tools">
            <?php if ($model->allowComment) : ?>
                <a href="<?= Url::to(['trx-nearmiss/response', 'id' => $model->id]) ?>" class="btn btn-sm btn-success"><i class="fa fa-reply-all margin-r-5"></i> Response</a>
            <?php endif; ?>
            <?php if ($model->isAuthor && !$model->isClose) : ?>
                <a href="<?= Url::to(['trx-nearmiss/closing', 'id' => $model->id]) ?>" class="btn btn-sm btn-warning"><i class="fa fa-close margin-r-5"></i> Closing</a>
            <?php endif; ?>
        </div>

    </div>
    <div class="box-body">
        <!-- Post -->
        <strong> 
            <?= $model->getAttributeLabel('risk') . ' : <i>' . $model->riskLookup->name . '</i>' ?> | Kemungkinan : <i><?= $model->posibilityLookup->name ?> </i> |
            Tingkatan Resiko : <i><?= $model->risk_level ?></i>
        </strong> <br/>
        <strong><i class="fa fa-comment-o margin-r-5"></i> Pembicaraan : </strong>
        <p> 
            <?= HtmlPurifier::process($model->description) ?> 
        </p>
        <strong><i class="fa fa-comments-o margin-r-5"></i>Tindakan Yang Disepakati :</strong>
        <p>
            <?= HtmlPurifier::process($model->problems) ?> 
        </p>
        <?= $model->getAttributeLabel('potency') ?><strong><?= ' : <i>' . $model->potencyLookup->name . '</i>' ?> </strong> 
        <?= $model->getAttributeLabel('involved') ?> <strong><?= ' : <i>' . $model->involvedLookup->name . '</i>' ?></strong>
        <br/>
        <strong><i class="fa fa-users margin-r-5"></i> Recomended Solution :</strong>
    </div>
    <div class="box-footer box-comments">
        <div class="box-comments">
            <?php foreach ($model->trxNearmissDetails as $item): ?>
                <div class="box-comment">
                    <img class="img-circle img-sm" src="<?= \Yii::$app->request->BaseUrl . '/img/user3-128x128.jpg' ?>" alt="User Image">
                    <div class="comment-text">
                        <span class="username"><?= $item->forUser->username; ?> [<?= $item->status ?>]
                            <span class="text-muted pull-right">Dead Line : <?= date('d-m-Y H::s', strtotime($item->do_date)) ?></span>
                        </span>
                        <?= HtmlPurifier::process($item->notes); ?>
                    </div>
                </div>

            <?php endforeach; ?>
        </div>
        <span class="text-muted">Follow Up (<?= $model->commentCount ?>)</span>
        <?php foreach ($model->trxNearmissComments as $item): ?>
            <div class="box-comment">
                <img class="img-circle img-sm" src="<?= \Yii::$app->request->BaseUrl . '/img/user5-128x128.jpg' ?>" alt="User Image">
                <div class="comment-text">
                    <span class="username">
                    <?= $item->postBy->username; ?> [<?= $item->status ?>]
                        <span class="text-muted pull-right">Posting At : <?= date('d-m-Y H:i:s', strtotime($item->created_at)); ?></span>
                    </span>
                    <?= HtmlPurifier::process($item->content) ?>
                </div>
            </div>

        <?php endforeach; ?>
    </div>


    <div class="overlay" style="display:none;">
        <i class="fa fa-refresh fa-spin"></i>
    </div>
</div>

views/trx-nearmiss/index.php
<?php
use yii\widgets\ListView;
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $searchModel app\models\search\TrxNearmissSeach */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Nearmiss');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="callout callout-info" style="padding: 5px 10px 20px 10px;">
    <h5><i class="fa fa-info"></i> Note : </h5>
    Click Add button to create new Nearmiss
    <?= Html::a('<i class="fa fa-plus"></i> Add',['create'],['class'=>'btn btn-sm btn-primary pull-right']); ?>
</div>
<?= ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_item',
    'summary'=>'',
]);
?>

<?php ob_start(); // output buffer the javascript to register later  ?>
<script>
    
</script>
<?php $this->registerJs(str_replace(['<script>', '</script>'], '', ob_get_clean())); ?> 

views/trx-nearmiss/response.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\HtmlPurifier;

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Nearmiss'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->params['breadcrumbs'][] = 'Response';

$imageUrl = Yii::getAlias('@web').'/img/user1-128x128.jpg';
if(!empty($model->posUser->image_path) && file_exists(Yii::getAlias('@web').$model->posUser->image_path)){
    $imageUrl = Yii::getAlias('@web').$model->posUser->image_path;
}

?>
<div class="box box-info trx-conversation-index">
    <div class="box-header with-border">
        <div class="user-block">
            <img class="img-circle img-bordered-sm" src="<?= $imageUrl; ?>" alt="user image">
            <span class="username">
                <a href="#"><?= $model->postBy->fullname ?></a>
            </span>
            <span class="description">
                <i>Lokasi :</i>
                <strong><i class="fa fa fa-map-marker margin-r-5"></i><?= $model->location->location_name ?></strong>
                , <i>Area :</i>
                <strong><?= $model->area->area_name; ?> </strong>
                , <i>Posting :</i> <?= date('d-m-Y H:i:s', strtotime($model->created_at)); ?>
            </span>
        </div>      
        <div class="box-tools">
            <?php if ($model->allowComment) : ?>
                <a href="<?= Url::to(['trx-nearmiss/response', 'id' => $model->id]) ?>" class="btn btn-sm btn-success"><i class="fa fa-reply-all margin-r-5"></i> Response</a>
            <?php endif; ?>
            <?php if ($model->isAuthor && !$model->isClose) : ?>
                <a href="<?= Url::to(['trx-nearmiss/closing', 'id' => $model->id]) ?>" class="btn btn-sm btn-warning"><i class="fa fa-close margin-r-5"></i> Closing</a>
            <?php endif; ?>
        </div>

    </div>
    <div class="box-body">
        <!-- Post -->
        <strong> 
            <?= $model->getAttributeLabel('risk') . ' : <i>' . $model->riskLookup->name . '</i>' ?> | Kemungkinan : <i><?= $model->posibilityLookup->name ?> </i> |
            Tingkatan Resiko : <i><?= $model->risk_level ?></i>
        </strong> <br/>
        <strong><i class="fa fa-comment-o margin-r-5"></i> Pembicaraan : </strong>
        <p> 
            <?= HtmlPurifier::process($model->description) ?> 
        </p>
        <strong><i class="fa fa-comments-o margin-r-5"></i>Tindakan Yang Disepakati :</strong>
        <p>
            <?= HtmlPurifier::process($model->problems) ?> 
        </p>
        <?= $model->getAttributeLabel('potency') ?><strong><?= ' : <i>' . $model->potencyLookup->name . '</i>' ?> </strong> 
        <?= $model->getAttributeLabel('involved') ?> <strong><?= ' : <i>' . $model->involvedLookup->name . '</i>' ?></strong>
        <br/>
        <strong><i class="fa fa-reply-all margin-r-5"></i> Need Response : </strong>
        <p>
            <?= HtmlPurifier::process($detail->notes) ?> 
        </p>
    </div>
    
        <!-- /.post -->
        <?php
        if ($model->allowComment || $model->isAuthor) {
            echo '<div class="box-footer">';
            echo $this->render('_comment', ['model' => $comment]);
            echo '</div>';
        }
        ?>    
    </div>  
    <div class="overlay" style="display:none;">
        <i class="fa fa-refresh fa-spin"></i>
    </div>
</div>

<?php ob_start(); // output buffer the javascript to register later   ?>
<script>
    
</script>
<?php $this->registerJs(str_replace(['<script>', '</script>'], '', ob_get_clean())); ?> 